### PR TITLE
Gv/ex03 b

### PR DESCRIPTION
**Pull request by giovannivolpe**

### CODE REVIEW

**Comment by BenjaminMidtvedt** [comment]
In cell 7, you can simply do `random_split(dataset, [0.8, 0.2])`. I'm also not entirely convinced we should operate on a subset of the full dataset. Why do we need this?

**Comment by BenjaminMidtvedt** [comment]
I also get the following error at the roc curve:

<details>
<summary>Error</summary>
<br>
```py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[c:\Users\GU\DeepLearningCrashCourse\Ch03_CNN\Ex03B\blood_smears.ipynb](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/blood_smears.ipynb) Cell 30 line <cell line: 3>()
      [1](vscode-notebook-cell:/c%3A/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/blood_smears.ipynb#X40sZmlsZQ%3D%3D?line=0) from fnc_blood_smears import plot_roc
----> [3](vscode-notebook-cell:/c%3A/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/blood_smears.ipynb#X40sZmlsZQ%3D%3D?line=2) _ = plot_roc(classifier=dnn_classifier, dataset=test)

File [c:\Users\GU\DeepLearningCrashCourse\Ch03_CNN\Ex03B\fnc_blood_smears.py:23](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:23), in plot_roc(classifier, dataset)
     [20](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:20) pred = classifier(tensor(stack(images))).tolist()
     [22](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:22) # calculate the ROC curve
---> [23](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:23) fpr, tpr, thresholds = roc_curve(gt, pred, pos_label=1) 
     [24](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:24) roc = auc(fpr, tpr) 
     [26](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:26) # plot the ROC curve

File [c:\Users\GU\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_ranking.py:981](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:981), in roc_curve(y_true, y_score, pos_label, sample_weight, drop_intermediate)
    [892](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:892) def roc_curve(
    [893](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:893)     y_true, y_score, *, pos_label=None, sample_weight=None, drop_intermediate=True
    [894](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:894) ):
    [895](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:895)     """Compute Receiver operating characteristic (ROC).
    [896](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:896) 
    [897](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:897)     Note: this implementation is restricted to the binary classification task.
   (...)
    [979](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:979) 
    [980](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:980)     """
--> [981](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:981)     fps, tps, thresholds = _binary_clf_curve(
    [982](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:982)         y_true, y_score, pos_label=pos_label, sample_weight=sample_weight
    [983](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:983)     )
    [985](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:985)     # Attempt to drop thresholds corresponding to points in between and
    [986](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:986)     # collinear with other points. These are always suboptimal and do not
    [987](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:987)     # appear on a plotted ROC curve (and thus do not affect the AUC).
   (...)
    [992](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:992)     # but does not drop more complicated cases like fps = [1, 3, 7],
    [993](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:993)     # tps = [1, 2, 4]; there is no harm in keeping too many thresholds.
    [994](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:994)     if drop_intermediate and len(fps) > 2:

File [c:\Users\GU\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_ranking.py:740](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:740), in _binary_clf_curve(y_true, y_score, pos_label, sample_weight)
    [738](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:738) y_type = type_of_target(y_true, input_name="y_true")
    [739](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:739) if not (y_type == "binary" or (y_type == "multiclass" and pos_label is not None)):
--> [740](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:740)     raise ValueError("{0} format is not supported".format(y_type))
    [742](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:742) check_consistent_length(y_true, y_score, sample_weight)
    [743](file:///C:/Users/GU/AppData/Local/Programs/Python/Python310/lib/site-packages/sklearn/metrics/_ranking.py:743) y_true = column_or_1d(y_true)

ValueError: unknown format is not supported
```
</details>

**Comment by cmanzo** [comment]
> In cell 7, you can simply do `random_split(dataset, [0.8, 0.2])`. I'm also not entirely convinced we should operate on a subset of the full dataset. Why do we need this?

without the subset it's kind of slow and does not really add much to the results

**Comment by BenjaminMidtvedt** [comment]
> > In cell 7, you can simply do `random_split(dataset, [0.8, 0.2])`. I'm also not entirely convinced we should operate on a subset of the full dataset. Why do we need this?
> 
> without the subset it's kind of slow and does not really add much to the results

What is slow? Training can be done in fewer epochs

**Comment by cmanzo** [comment]
In cell 1, withouth these lines:

```import ssl
ssl._create_default_https_context = ssl._create_unverified_context```

I cannot download the data. It might be worth commenting on that in case others have the same issue

**Comment by cmanzo** [comment]
> Reference

That's weird... the ROC curve works fine for me...

**Comment by BenjaminMidtvedt** [comment]
One possibility is to use torchmetric ROC instead of skimage. it integrates nicer with torch:

```py
roc = tm.ROC(task="binary")

for batch in test_loader:
    x, y = batch
    y_pred = dnn_classifier(x)
    roc.update(y_pred, y.long(

))

roc.plot()
```

roc

**Comment by BenjaminMidtvedt** [comment]
I guess my final comments are a bit minor.

- Why a larger test batch size than training?
- What are the transforms we define from torchvision, what do they do (conceptually, not literally).
- We say that we do abs(1 - target) to assign indexes to the classes, but it feels a bit out of the blue. What are `targets` here, and why do we flip them? (to make infected = positive, which is standard for medical statistical analysis).
- We mix quite randomly importing the module `import numpy as np` with importing individual functions `from torch import cat`. Might be worth to standardize a choice (I prefer importing modules and namespaces, you end up spending less lines on imports).

**Review by BenjaminMidtvedt — COMMENTED** [review]
`images_idx` doesn't seem to be used anywhere

`tensor(np.stack(images))` can be `torch.stack(images)` (also np is not imported)
in the same cell, I get an error
```
TypeError                                 Traceback (most recent call last)
[c:\Users\GU\DeepLearningCrashCourse\Ch03_CNN\Ex03B\blood_smears.ipynb](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/blood_smears.ipynb) Cell 43 line <cell line: 8>()
      [5](vscode-notebook-cell:/c%3A/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/blood_smears.ipynb#Y263sZmlsZQ%3D%3D?line=4) images, gt = zip(*test)
      [6](vscode-notebook-cell:/c%3A/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/blood_smears.ipynb#Y263sZmlsZQ%3D%3D?line=5) pred = cnn_classifier(stack(images)).tolist()
----> [8](vscode-notebook-cell:/c%3A/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/blood_smears.ipynb#Y263sZmlsZQ%3D%3D?line=7) plot_failures(images, gt, pred)

File [c:\Users\GU\DeepLearningCrashCourse\Ch03_CNN\Ex03B\fnc_blood_smears.py:31](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:31), in plot_failures(images, gt, pred, threshold, plot_num)
     [28](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:28) for i in range(plot_num):
     [29](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:29)     # false positives
     [30](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:30)     plt.subplot(2, plot_num, i + 1)
---> [31](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:31)     plt.imshow(false_positives_images[i].transpose(1, 2, 0))
     [32](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:32)     if i == 0:
     [33](file:///C:/Users/GU/DeepLearningCrashCourse/Ch03_CNN/Ex03B/fnc_blood_smears.py:33)         plt.title("False positives", fontsize=16, y=1.1)

TypeError: transpose() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int dim0, int dim1)
 * (name dim0, name dim1)
```

In the grad cam, it might be better to have a fixed image. I got an image where it didn't work (I think the parasite was too close to the border of the image)

**Comment by BenjaminMidtvedt** [comment]
There's also an extra whitespace in `roc_cnn.update( cnn_classifier(x), y.long())`

**Comment by giovannivolpe** [comment]
@cmanzo are the last comments by Benjamin already implemented, right?

**Comment by cmanzo** [comment]
> @cmanzo are the last comments by Benjamin already implemented, right?

Yes!

**Pull request merged**
